/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include "led.h"
#include "uart.h"
#include "osKernel.h"

#define QUANTA 10
#define UART_RX_QUEUE_SIZE 32

typedef volatile uint32_t TaskProfiler;
TaskProfiler Task0_Profiler, Task1_Profiler, Task2_Profiler, Periodic_Task1_Profiler, Periodic_Task2_Profiler;
volatile uint32_t Overflow_Test_Profiler;

int32_t semaphore1,  semaphore2;
static uint8_t uart_rx_buffer[UART_RX_QUEUE_SIZE];
osQueue_t uart_rx_queue;

// define mutex to protect hardware resource like uart printf
osMutex_t print_mutex;

// Motor timer replaces task0
// Same 100ms period as before but costs ~20 bytes instead of a full TCB + 1600 byte stack
osTimer_t motor_timer;

// Periodic CPU usage reporter
// Runs every 5 seconds in the timer service task context so printf is safe
// Output is a top-like snapshot showing per-task percentages plus system idle
osTimer_t cpu_report_timer;

void motor_run(void);
void motor_stop(void);
void valve_open(void);
void valve_close(void);


// USART2 Interrupt Service Routine
// This function handles USART2 global interrupt.
// It is automatically called by the hardware (or Keil simulator)
// when a character is received on PA3 (UART2_RX)
void USART2_IRQHandler(void) {
		// Check if RXNE (Read Data Register Not Empty) interrupt flag is set
    // RXNE flag means a new byte is sitting in DR waiting to be read
    if (USART2->SR & (1U<<5)) {
        uint8_t byte = USART2->DR;   // reading DR also clears the RXNE flag

        // Push into the queue, non-blocking so ISR returns immediately
        // Return value is ignored here because we have no good recovery in ISR context
        // If the queue fills up the byte is dropped, which is the correct behavior
        // (better to lose one character than to stall the ISR and miss subsequent interrupts)
        osQueueSend(&uart_rx_queue, byte);
    }
}

/*
//If we see particular task profiler is not being incremented
//This shows that our thread is not running
void task0(void) {
	while (1) {
		Task0_Profiler++;
		osThreadYield();
		osMutexAcquire(&print_mutex);
		motor_run();
		osMutexRelease(&print_mutex);
		osDelay(10);
		}
}
*/

// Runs in timer service task context, so mutexes and printf are safe
// If this were called from ISR directly we could not use print_mutex here
void motor_timer_callback(void) {
    osMutexAcquire(&print_mutex);
    motor_run();
    osMutexRelease(&print_mutex);
}

// CPU usage reporter callback
// Sums all run ticks, converts each task's share to a percentage, prints a table
// Then resets all counters so the next report reflects only the next 5 second window
// Runs in timer service task context, safe to use mutex and printf
void cpu_report_callback(void) {
    uint32_t count = osGetTaskCount();
    uint32_t total = 0;

    // Sum all task ticks to get the denominator for percentage math
    // Total ticks should be close to 500 (5 seconds * 100Hz) but slight drift is normal
    for (uint32_t i = 0; i < count; i++) {
        total += osGetTaskRunTicks(i);
    }

    // Guard against the impossible-but-possible case of total being 0
    // This could happen right after reset before any tick has accumulated
    if (total == 0) {
        return;
    }

    osMutexAcquire(&print_mutex);

    printf("\n==== CPU USAGE ====\n\r");
    for (uint32_t i = 0; i < count; i++) {
        // Integer percentage math: multiply before divide to preserve precision
        // Otherwise tasks under 1% would show as 0
        uint32_t ticks = osGetTaskRunTicks(i);
        uint32_t pct = (ticks * 100) / total;

        // Index 0 is always the idle task by kernel convention
        // Labeling it explicitly helps read the report at a glance
        if (i == 0) {
					printf("Idle         : %u%% (%u ticks)\n\r", pct, ticks);
				} else {
					printf("Task %u       : %u%% (%u ticks)\n\r", i, pct, ticks);
				}
    }
    printf("Total ticks  : %u\n\r", total);
    printf("===================\n\r");

    osMutexRelease(&print_mutex);

    // Fresh window for the next report, otherwise percentages become lifetime averages
    // and gradually lose sensitivity to current system behavior
    osResetAllRunTicks();
}


void task1(void) {
	while (1) {
		Task1_Profiler++;
		osSemaphoreWait(&semaphore1);
		osMutexAcquire(&print_mutex);
		valve_open();
		osMutexRelease(&print_mutex);
		osSemaphoreSet(&semaphore2);
		osDelay(10);
		}
}


void task2(void) {
	while (1) {
		Task2_Profiler++;
		osSemaphoreWait(&semaphore2);
		osMutexAcquire(&print_mutex);
		valve_close();
		osMutexRelease(&print_mutex);
		osSemaphoreSet(&semaphore1);
		osDelay(10);
		}
}

//periodic scheduler
void task3(void) {
	Periodic_Task1_Profiler++;
}

// UART Listener (Event-Driven Task)
// This task sleeps and waits for UART data
// It consumes 0 CPU cycles until the ISR gives the semaphore
void task4(void) {
    uint8_t rx_byte;

    while (1) {
        // Block until the ISR puts something into the queue
        // Zero CPU cost while waiting, task is in sleeping state
        osQueueReceive(&uart_rx_queue, &rx_byte);

				 osMutexAcquire(&print_mutex);
			
        // Process the command we just received
        if (rx_byte == 'O') {
            printf("Receive\n");
            valve_open();
        }
        else if (rx_byte == 'C') {
            printf("Receive\n");
            valve_close();
        }
				osMutexRelease(&print_mutex);
        // Unknown bytes are silently ignored, could add logging later if needed
    }
	}
	

// Test task: intentionally overflows its stack to verify the canary detector
// Allocates a local array larger than STACK_SIZE (1600 bytes) which forces
// SP to drop below the canary and corrupt the bottom of the stack
// On the next context switch the scheduler should catch this and halt the system
// Remove this task and its osKernelAddThread line once the canary is verified working
/* void overflow_test_task(void) {
    while (1) {
				Overflow_Test_Profiler++;
        // 2000 byte local array, stack is only 1600 byte so this guarantees overflow
        // volatile prevents the optimizer from removing the array since we never read it meaningfully
        volatile uint8_t bomb[2000];

        // Touch both ends so the compiler must actually reserve the full range on the stack
        // Without these writes the optimizer might shrink or eliminate the allocation entirely
        bomb[0] = 0xFF;
        bomb[1999] = 0xFF;
			
				// Busy loop keeps SP low long enough for SysTick to fire while we are here
        // Without this the function returns too quickly and SP is back to normal
        // by the time the scheduler saves it, so the check sees a healthy SP
        for (volatile uint32_t i = 0; i < 100000; i++) {
            bomb[i % 2000] = (uint8_t)i;  // also keeps writing so array stays live
        }

        osDelay(10);
    }
}
*/

/*
// Test task: simulates UART RX interrupt in software
// Use this when testing queue behavior without a real UART simulator
// Just pushes characters into the queue as if they came from the ISR
void uart_test_task(void) {
    const char *test_sequence = "OCOCOC";
    uint32_t i = 0;
    
    while (1) {
        // Inject one character into the queue, same as the ISR would
        osQueueSend(&uart_rx_queue, test_sequence[i]);
        i = (i + 1) % 6;  // loop through O-C-O-C-O-C forever
        
        osDelay(50);  // 500ms between characters, enough to see task4 drain
    }
}
*/

void uart_test_task(void) {
    while (1) {
        // Inject 5 characters back-to-back (simulates a UART burst at high baud rate)
        // This is where the queue proves its worth: old single-slot latest_rx_data
        // would lose 4 out of 5 characters, queue catches all of them
        osQueueSend(&uart_rx_queue, 'O');
        osQueueSend(&uart_rx_queue, 'C');
        osQueueSend(&uart_rx_queue, 'O');
        osQueueSend(&uart_rx_queue, 'C');
        osQueueSend(&uart_rx_queue, 'O');

        osDelay(200);  // 2 second gap between bursts
    }
}

int main() {
	// To prevent nested interrupts
	__disable_irq();
	
	// Initialize UART (TX and RX Interrupts)
	uart_tx_init();
	// uart_rx_interrupt_init(); // disabled to isolate queue test from simulator noise

	// Initialize hardware timer
	tim2_1hz_interrupt_init();

	// Initialize semaphores
	osSemaphoreInit(&semaphore1, 1);
	osSemaphoreInit(&semaphore2, 0);
	
	// Initialize the UART RX queue with its backing buffer
	osQueueInit(&uart_rx_queue, uart_rx_buffer, UART_RX_QUEUE_SIZE);
	
	// Initialize mutex
	osMutexInit(&print_mutex);
	
	// Arm the motor timer: period 10 ticks = 100ms (TIM2 runs at 100Hz)
	// Periodic flag = 1 means auto-reload after each expiration
	osTimerCreate(&motor_timer, 10, 1, motor_timer_callback);
	osTimerStart(&motor_timer);
	
	// CPU usage report every 5 seconds (500 ticks * 10ms)
	// Uses the same timer service infrastructure as motor_timer, no extra task needed
	osTimerCreate(&cpu_report_timer, 500, 1, cpu_report_callback);
	osTimerStart(&cpu_report_timer);

	//Initialize kernel
	osKernelInit(SCHED_PRIORITY);

	//Add thread
	// osKernelAddThreads(&task0, &task1, &task2, &task4);

	// Add threads dynamically to the kernel
	// We can check the return values for debugging if we want
  // osKernelAddThread(&task0, 0);
	
	// Timer service gets highest priority so callbacks have low latency
	// It blocks when idle so this does not starve other tasks
	osKernelAddThread(&osTimerServiceTask, 0);
	
  osKernelAddThread(&task1, 1);
	osKernelAddThread(&task2, 2);

	// Task 4 (UART Listener)
	osKernelAddThread(&task4, 3);
	
	// To tes queue
	osKernelAddThread(&uart_test_task, 4);
	
	// DEBUG ONLY: stack overflow detector test task
	// Should trigger osStackOverflowHandler within the first few ticks
	// Comment out this line to disable the test and return to normal operation
	// osKernelAddThread(&overflow_test_task, 4);

	// Set round robin time quanta
	osKernelLaunch(QUANTA);

	while (1) {
	// CPU should never reach here if OS is running
	}
}

void TIM2_IRQHandler(void) {
    // Clear update interrupt flag to acknowledge the interrupt
    TIM2->SR &= ~SR_UIF;

    // Decrement all sleeping tasks' counters
    // We use TIM2 instead of SysTick because osThreadYield() resets SysTick->VAL
    // which also clears COUNTFLAG, making SysTick-based timing unreliable
    osTickDecrement();
	
	
    // Advance software timers, expired ones get pushed to the service task
    // This single line is the hook that drives the entire timer subsystem
    osTimerTick();
	
		// CPU usage accounting: credit this tick to whichever task is currently running
    // currentPt is set by osKernelLaunch and always points to a valid task from then on
    // If we are in the idle task, idle gets the tick - which is exactly what we want
    osAccountCurrentTick();

    // Profiler for debugging the periodic ISR
    Periodic_Task2_Profiler++;
}

void motor_run(void) {
	printf("Motor is starting...\n\r");
}

void motor_stop(void) {
	printf("Motor is stopping...\n\r");
}

void valve_open(void) {
	printf("Valve is opening...\n\r");
}

void valve_close(void) {
	printf("Valve is closing...\n\r");
}
